import { ICDefinition, ICType, Pin } from '@/types/circuit';

// Generate pins for an IC
const generatePins = (
  pinCount: number,
  pinConfig: Partial<Record<number, { name: string; type: Pin['type'] }>>
): Pin[] => {
  const pins: Pin[] = [];
  const halfPins = pinCount / 2;

  for (let i = 1; i <= pinCount; i++) {
    const isLeftSide = i <= halfPins;
    const config = pinConfig[i] || { name: `P${i}`, type: 'input' as const };
    
    const posIndex = isLeftSide ? i - 1 : pinCount - i;
    
    pins.push({
      id: `pin-${i}`,
      name: config.name,
      type: config.type,
      position: {
        x: isLeftSide ? 0 : 1,
        y: posIndex / (halfPins - 1),
      },
      side: isLeftSide ? 'left' : 'right',
      state: 0,
    });
  }

  return pins;
};

export const IC_DEFINITIONS: Record<ICType, ICDefinition> = {
  '7404': {
    type: '7404',
    name: '74LS04',
    description: 'Hex Inverter (NOT gates)',
    pinCount: 14,
    category: 'gate',
    pins: generatePins(14, {
      1: { name: '1A', type: 'input' },
      2: { name: '1Y', type: 'output' },
      3: { name: '2A', type: 'input' },
      4: { name: '2Y', type: 'output' },
      5: { name: '3A', type: 'input' },
      6: { name: '3Y', type: 'output' },
      7: { name: 'GND', type: 'ground' },
      8: { name: '4Y', type: 'output' },
      9: { name: '4A', type: 'input' },
      10: { name: '5Y', type: 'output' },
      11: { name: '5A', type: 'input' },
      12: { name: '6Y', type: 'output' },
      13: { name: '6A', type: 'input' },
      14: { name: 'VCC', type: 'power' },
    }),
  },

  '7408': {
    type: '7408',
    name: '74LS08',
    description: 'Quad 2-Input AND Gates',
    pinCount: 14,
    category: 'gate',
    pins: generatePins(14, {
      1: { name: '1A', type: 'input' },
      2: { name: '1B', type: 'input' },
      3: { name: '1Y', type: 'output' },
      4: { name: '2A', type: 'input' },
      5: { name: '2B', type: 'input' },
      6: { name: '2Y', type: 'output' },
      7: { name: 'GND', type: 'ground' },
      8: { name: '3Y', type: 'output' },
      9: { name: '3A', type: 'input' },
      10: { name: '3B', type: 'input' },
      11: { name: '4Y', type: 'output' },
      12: { name: '4A', type: 'input' },
      13: { name: '4B', type: 'input' },
      14: { name: 'VCC', type: 'power' },
    }),
  },

  '7432': {
    type: '7432',
    name: '74LS32',
    description: 'Quad 2-Input OR Gates',
    pinCount: 14,
    category: 'gate',
    pins: generatePins(14, {
      1: { name: '1A', type: 'input' },
      2: { name: '1B', type: 'input' },
      3: { name: '1Y', type: 'output' },
      4: { name: '2A', type: 'input' },
      5: { name: '2B', type: 'input' },
      6: { name: '2Y', type: 'output' },
      7: { name: 'GND', type: 'ground' },
      8: { name: '3Y', type: 'output' },
      9: { name: '3A', type: 'input' },
      10: { name: '3B', type: 'input' },
      11: { name: '4Y', type: 'output' },
      12: { name: '4A', type: 'input' },
      13: { name: '4B', type: 'input' },
      14: { name: 'VCC', type: 'power' },
    }),
  },

  '7400': {
    type: '7400',
    name: '74LS00',
    description: 'Quad 2-Input NAND Gates',
    pinCount: 14,
    category: 'gate',
    pins: generatePins(14, {
      1: { name: '1A', type: 'input' },
      2: { name: '1B', type: 'input' },
      3: { name: '1Y', type: 'output' },
      4: { name: '2A', type: 'input' },
      5: { name: '2B', type: 'input' },
      6: { name: '2Y', type: 'output' },
      7: { name: 'GND', type: 'ground' },
      8: { name: '3Y', type: 'output' },
      9: { name: '3A', type: 'input' },
      10: { name: '3B', type: 'input' },
      11: { name: '4Y', type: 'output' },
      12: { name: '4A', type: 'input' },
      13: { name: '4B', type: 'input' },
      14: { name: 'VCC', type: 'power' },
    }),
  },

  '7402': {
    type: '7402',
    name: '74LS02',
    description: 'Quad 2-Input NOR Gates',
    pinCount: 14,
    category: 'gate',
    pins: generatePins(14, {
      1: { name: '1Y', type: 'output' },
      2: { name: '1A', type: 'input' },
      3: { name: '1B', type: 'input' },
      4: { name: '2Y', type: 'output' },
      5: { name: '2A', type: 'input' },
      6: { name: '2B', type: 'input' },
      7: { name: 'GND', type: 'ground' },
      8: { name: '3A', type: 'input' },
      9: { name: '3B', type: 'input' },
      10: { name: '3Y', type: 'output' },
      11: { name: '4A', type: 'input' },
      12: { name: '4B', type: 'input' },
      13: { name: '4Y', type: 'output' },
      14: { name: 'VCC', type: 'power' },
    }),
  },

  '7486': {
    type: '7486',
    name: '74LS86',
    description: 'Quad 2-Input XOR Gates',
    pinCount: 14,
    category: 'gate',
    pins: generatePins(14, {
      1: { name: '1A', type: 'input' },
      2: { name: '1B', type: 'input' },
      3: { name: '1Y', type: 'output' },
      4: { name: '2A', type: 'input' },
      5: { name: '2B', type: 'input' },
      6: { name: '2Y', type: 'output' },
      7: { name: 'GND', type: 'ground' },
      8: { name: '3Y', type: 'output' },
      9: { name: '3A', type: 'input' },
      10: { name: '3B', type: 'input' },
      11: { name: '4Y', type: 'output' },
      12: { name: '4A', type: 'input' },
      13: { name: '4B', type: 'input' },
      14: { name: 'VCC', type: 'power' },
    }),
  },

  '7474': {
    type: '7474',
    name: '74LS74',
    description: 'Dual D Flip-Flop with Preset & Clear',
    pinCount: 14,
    category: 'flip-flop',
    pins: generatePins(14, {
      1: { name: '1CLR', type: 'control' },
      2: { name: '1D', type: 'input' },
      3: { name: '1CLK', type: 'clock' },
      4: { name: '1PRE', type: 'control' },
      5: { name: '1Q', type: 'output' },
      6: { name: '1Q̄', type: 'output' },
      7: { name: 'GND', type: 'ground' },
      8: { name: '2Q̄', type: 'output' },
      9: { name: '2Q', type: 'output' },
      10: { name: '2PRE', type: 'control' },
      11: { name: '2CLK', type: 'clock' },
      12: { name: '2D', type: 'input' },
      13: { name: '2CLR', type: 'control' },
      14: { name: 'VCC', type: 'power' },
    }),
  },

  '7476': {
    type: '7476',
    name: '74LS76',
    description: 'Dual JK Flip-Flop with Preset & Clear',
    pinCount: 16,
    category: 'flip-flop',
    pins: generatePins(16, {
      1: { name: '1CLK', type: 'clock' },
      2: { name: '1PRE', type: 'control' },
      3: { name: '1CLR', type: 'control' },
      4: { name: '1J', type: 'input' },
      5: { name: 'VCC', type: 'power' },
      6: { name: '2CLK', type: 'clock' },
      7: { name: '2PRE', type: 'control' },
      8: { name: '2CLR', type: 'control' },
      9: { name: '2J', type: 'input' },
      10: { name: '2Q̄', type: 'output' },
      11: { name: '2Q', type: 'output' },
      12: { name: '2K', type: 'input' },
      13: { name: 'GND', type: 'ground' },
      14: { name: '1Q̄', type: 'output' },
      15: { name: '1Q', type: 'output' },
      16: { name: '1K', type: 'input' },
    }),
  },

  '7490': {
    type: '7490',
    name: '74LS90',
    description: 'Decade Counter (BCD)',
    pinCount: 14,
    category: 'counter',
    pins: generatePins(14, {
      1: { name: 'CKB', type: 'clock' },
      2: { name: 'R0(1)', type: 'control' },
      3: { name: 'R0(2)', type: 'control' },
      4: { name: 'NC', type: 'input' },
      5: { name: 'VCC', type: 'power' },
      6: { name: 'R9(1)', type: 'control' },
      7: { name: 'R9(2)', type: 'control' },
      8: { name: 'QC', type: 'output' },
      9: { name: 'QB', type: 'output' },
      10: { name: 'GND', type: 'ground' },
      11: { name: 'QD', type: 'output' },
      12: { name: 'QA', type: 'output' },
      13: { name: 'NC', type: 'input' },
      14: { name: 'CKA', type: 'clock' },
    }),
  },

  '7493': {
    type: '7493',
    name: '74LS93',
    description: '4-bit Binary Counter',
    pinCount: 14,
    category: 'counter',
    pins: generatePins(14, {
      1: { name: 'CKB', type: 'clock' },
      2: { name: 'R0(1)', type: 'control' },
      3: { name: 'R0(2)', type: 'control' },
      4: { name: 'NC', type: 'input' },
      5: { name: 'VCC', type: 'power' },
      6: { name: 'NC', type: 'input' },
      7: { name: 'NC', type: 'input' },
      8: { name: 'QC', type: 'output' },
      9: { name: 'QB', type: 'output' },
      10: { name: 'GND', type: 'ground' },
      11: { name: 'QD', type: 'output' },
      12: { name: 'QA', type: 'output' },
      13: { name: 'NC', type: 'input' },
      14: { name: 'CKA', type: 'clock' },
    }),
  },

  '74138': {
    type: '74138',
    name: '74LS138',
    description: '3-to-8 Line Decoder/Demultiplexer',
    pinCount: 16,
    category: 'decoder',
    pins: generatePins(16, {
      1: { name: 'A', type: 'input' },
      2: { name: 'B', type: 'input' },
      3: { name: 'C', type: 'input' },
      4: { name: 'G2A', type: 'control' },
      5: { name: 'G2B', type: 'control' },
      6: { name: 'G1', type: 'control' },
      7: { name: 'Y7', type: 'output' },
      8: { name: 'GND', type: 'ground' },
      9: { name: 'Y6', type: 'output' },
      10: { name: 'Y5', type: 'output' },
      11: { name: 'Y4', type: 'output' },
      12: { name: 'Y3', type: 'output' },
      13: { name: 'Y2', type: 'output' },
      14: { name: 'Y1', type: 'output' },
      15: { name: 'Y0', type: 'output' },
      16: { name: 'VCC', type: 'power' },
    }),
  },

  '74151': {
    type: '74151',
    name: '74LS151',
    description: '8-to-1 Data Selector/Multiplexer',
    pinCount: 16,
    category: 'mux',
    pins: generatePins(16, {
      1: { name: 'D3', type: 'input' },
      2: { name: 'D2', type: 'input' },
      3: { name: 'D1', type: 'input' },
      4: { name: 'D0', type: 'input' },
      5: { name: 'Y', type: 'output' },
      6: { name: 'W', type: 'output' },
      7: { name: 'G', type: 'control' },
      8: { name: 'GND', type: 'ground' },
      9: { name: 'C', type: 'input' },
      10: { name: 'B', type: 'input' },
      11: { name: 'A', type: 'input' },
      12: { name: 'D7', type: 'input' },
      13: { name: 'D6', type: 'input' },
      14: { name: 'D5', type: 'input' },
      15: { name: 'D4', type: 'input' },
      16: { name: 'VCC', type: 'power' },
    }),
  },

  '7447': {
    type: '7447',
    name: '74LS47',
    description: 'BCD to 7-Segment Decoder',
    pinCount: 16,
    category: 'display',
    pins: generatePins(16, {
      1: { name: 'B', type: 'input' },
      2: { name: 'C', type: 'input' },
      3: { name: 'LT', type: 'control' },
      4: { name: 'BI/RBO', type: 'control' },
      5: { name: 'RBI', type: 'control' },
      6: { name: 'D', type: 'input' },
      7: { name: 'A', type: 'input' },
      8: { name: 'GND', type: 'ground' },
      9: { name: 'e', type: 'output' },
      10: { name: 'd', type: 'output' },
      11: { name: 'c', type: 'output' },
      12: { name: 'b', type: 'output' },
      13: { name: 'a', type: 'output' },
      14: { name: 'g', type: 'output' },
      15: { name: 'f', type: 'output' },
      16: { name: 'VCC', type: 'power' },
    }),
  },
};

export const IC_CATEGORIES = {
  gate: {
    name: 'Logic Gates',
    icon: '⚡',
    ics: ['7404', '7408', '7432', '7400', '7402', '7486'] as ICType[],
  },
  'flip-flop': {
    name: 'Flip-Flops',
    icon: '🔄',
    ics: ['7474', '7476'] as ICType[],
  },
  counter: {
    name: 'Counters',
    icon: '🔢',
    ics: ['7490', '7493'] as ICType[],
  },
  decoder: {
    name: 'Decoders',
    icon: '📤',
    ics: ['74138'] as ICType[],
  },
  mux: {
    name: 'Multiplexers',
    icon: '🔀',
    ics: ['74151'] as ICType[],
  },
  display: {
    name: 'Display Drivers',
    icon: '💡',
    ics: ['7447'] as ICType[],
  },
};
